[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health/ready"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[services]]
name = "ecommerce-api"
source = "."

[[services.variables]]
name = "APP_ENV"
value = "production"

[[services.variables]]
name = "PORT"
value = "8000"

[[services.variables]]
name = "HOST"
value = "0.0.0.0"

# Database will be provided by Railway's PostgreSQL service
# Redis will be provided by Railway's Redis service